In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
path = "/content/drive/MyDrive/Colab Notebooks/WoC ML Project/melb_data.csv"

melb_df = pd.read_csv(path)
# melb_df = pd.read_excel(path, sheet_name = 'sheet1') - excel file remaining
# melb_df = pd.Dataframe(path, delimeter = ',' or ' ')
# melb_df = pd.read_table(path, sep='\t')

In [5]:
melb_df.head(2)

       Suburb          Address  ...             Regionname Propertycount
0  Abbotsford     85 Turner St  ...  Northern Metropolitan        4019.0
1  Abbotsford  25 Bloomburg St  ...  Northern Metropolitan        4019.0

[2 rows x 21 columns]

In [6]:
melb_df.shape

(13580, 21)

In [7]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [8]:
np.unique(melb_df.Car)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan])

In [9]:
cols = melb_df.columns

In [10]:
cols

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [11]:
np.unique(melb_df.Rooms)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [12]:
np.unique(melb_df.Type)

array(['h', 't', 'u'], dtype=object)

In [13]:
np.unique(melb_df.Method)

array(['PI', 'S', 'SA', 'SP', 'VB'], dtype=object)

In [14]:
np.unique(melb_df.BuildingArea)

array([ 0.,  1.,  2., ..., nan, nan, nan])

In [15]:
np.unique(melb_df.Bedroom2)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 20.])

In [16]:
np.unique(melb_df.Bathroom)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [17]:
melb_df['CouncilArea'].unique()

array(['Yarra', 'Moonee Valley', 'Port Phillip', 'Darebin', 'Hobsons Bay',
       'Stonnington', 'Boroondara', 'Monash', 'Glen Eira', 'Whitehorse',
       'Maribyrnong', 'Bayside', 'Moreland', 'Manningham', 'Banyule',
       'Melbourne', 'Kingston', 'Brimbank', 'Hume', nan, 'Knox',
       'Maroondah', 'Casey', 'Melton', 'Greater Dandenong', 'Nillumbik',
       'Whittlesea', 'Frankston', 'Macedon Ranges', 'Yarra Ranges',
       'Wyndham', 'Cardinia', 'Unavailable', 'Moorabool'], dtype=object)

In [18]:
melb_df.size

285180

In [19]:
melb_df.ndim

2

In [20]:
melb_df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [21]:
melb_df_copy = melb_df.copy(deep = True)

In [22]:
for val in melb_df_copy.Postcode:
  melb_df_copy['Postcode'] = int(val) 

melb_df_copy.Postcode = melb_df_copy.Postcode.astype('int64')

In [24]:
melb_df_copy.Type = melb_df_copy.Type.astype('category')

In [25]:
melb_df_copy.Method = melb_df_copy.Method.astype('category')

In [26]:
for val in melb_df_copy.Bedroom2:
  melb_df_copy['Bedroom2'] = int(val)

melb_df_copy.Bedroom2 = melb_df_copy.Bedroom2.astype('int64')

In [27]:
for val in melb_df_copy.Bathroom:
  melb_df_copy['Bathroom'] = int(val)

melb_df_copy.Bathroom = melb_df_copy.Bathroom.astype('int64')

In [28]:
for val in melb_df_copy.Propertycount:
  melb_df_copy['Propertycount'] = int(val)

melb_df_copy.Propertycount = melb_df_copy.Propertycount.astype('int64')

In [29]:
melb_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  category
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  category
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  int64
 10  Bedroom2       13580 non-null  int64
 11  Bathroom       13580 non-null  int64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  int64
dtypes: category(2), float64(8), int64(5), object(6)
memory usage: 2.0+ MB

#**Data Cleaning**

There are 2 ways to do data cleaning
+ Data filling 
+ Drop off the data

#**Imp Tips**
+ Droping of data is not prefered as we are going to drop some valuable data. 
+ If you already have huge amout of data then droping of data is last option preferred.
+ So, data filling is genereally used and important to learn and so we'll use pandas inbuilt datafilling techniques like: bfill, ffill, etc.

We'll now see both the techniques one by one.
1.   Drop Na values

In [30]:
melb_df_drop = melb_df_copy.copy(deep = True)

In [37]:
melb_df_drop.dropna(inplace = True)

In [38]:
melb_df_drop.size

130116

In [40]:
melb_df.size

285180

We can now observe that almost 50 percent of the data is lost!!

In [41]:
melb_df_drop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6196 entries, 1 to 12212
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         6196 non-null   object
 1   Address        6196 non-null   object
 2   Rooms          6196 non-null   int64
 3   Type           6196 non-null   category
 4   Price          6196 non-null   float64
 5   Method         6196 non-null   category
 6   SellerG        6196 non-null   object
 7   Date           6196 non-null   object
 8   Distance       6196 non-null   float64
 9   Postcode       6196 non-null   int64
 10  Bedroom2       6196 non-null   int64
 11  Bathroom       6196 non-null   int64
 12  Car            6196 non-null   float64
 13  Landsize       6196 non-null   float64
 14  BuildingArea   6196 non-null   float64
 15  YearBuilt      6196 non-null   float64
 16  CouncilArea    6196 non-null   object
 17  Lattitude      6196 non-null   float64
 18  Longtitude     6196 non-null   float64
 19  Regionname     6196 non-null   object
 20  Propertycount  6196 non-null   int64
dtypes: category(2), float64(8), int64(5), object(6)
memory usage: 980.5+ KB

In [42]:
melb_df_drop.memory_usage()

Index            49568
Suburb           49568
Address          49568
Rooms            49568
Type              6300
Price            49568
Method            6396
SellerG          49568
Date             49568
Distance         49568
Postcode         49568
Bedroom2         49568
Bathroom         49568
Car              49568
Landsize         49568
BuildingArea     49568
YearBuilt        49568
CouncilArea      49568
Lattitude        49568
Longtitude       49568
Regionname       49568
Propertycount    49568
dtype: int64

In [43]:
melb_df_drop.size

130116

In [45]:
for val in melb_df_drop.Car:
  melb_df_drop['Car'] = int(val)

melb_df_drop.Car = melb_df_drop.Car.astype('int64')

In [46]:
melb_df_drop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6196 entries, 1 to 12212
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         6196 non-null   object
 1   Address        6196 non-null   object
 2   Rooms          6196 non-null   int64
 3   Type           6196 non-null   category
 4   Price          6196 non-null   float64
 5   Method         6196 non-null   category
 6   SellerG        6196 non-null   object
 7   Date           6196 non-null   object
 8   Distance       6196 non-null   float64
 9   Postcode       6196 non-null   int64
 10  Bedroom2       6196 non-null   int64
 11  Bathroom       6196 non-null   int64
 12  Car            6196 non-null   int64
 13  Landsize       6196 non-null   float64
 14  BuildingArea   6196 non-null   float64
 15  YearBuilt      6196 non-null   float64
 16  CouncilArea    6196 non-null   object
 17  Lattitude      6196 non-null   float64
 18  Longtitude     6196 non-null   float64
 19  Regionname     6196 non-null   object
 20  Propertycount  6196 non-null   int64
dtypes: category(2), float64(7), int64(6), object(6)
memory usage: 980.5+ KB

2. Data Filling

+ backfill/ bfill - fills the empty cell with the next valid value.
+ pad/ ffill - fills the empty cell with the last valid value encountered till now.

+ Other standard technique is filling the categorical data with the modal value and numeric data with mean/ median value. This technique is used to clean particular feature of the data.

In [58]:
melb_df_copy.fillna(method = 'bfill', inplace = True)

For example variable **Car** can be filled using the **modal** value as its a categorical feature(though it has integral enteries of the number of cars). We can fill the column like **Price** with the **mean/ median** of that particular feature.

In [49]:
melb_df.describe()

              Rooms         Price  ...    Longtitude  Propertycount
count  13580.000000  1.358000e+04  ...  13580.000000   13580.000000
mean       2.937997  1.075684e+06  ...    144.995216    7454.417378
std        0.955748  6.393107e+05  ...      0.103916    4378.581772
min        1.000000  8.500000e+04  ...    144.431810     249.000000
25%        2.000000  6.500000e+05  ...    144.929600    4380.000000
50%        3.000000  9.030000e+05  ...    145.000100    6555.000000
75%        3.000000  1.330000e+06  ...    145.058305   10331.000000
max       10.000000  9.000000e+06  ...    145.526350   21650.000000

[8 rows x 13 columns]

In [50]:
melb_df_drop.describe()

             Rooms         Price  ...   Longtitude  Propertycount
count  6196.000000  6.196000e+03  ...  6196.000000         6196.0
mean      2.931407  1.068828e+06  ...   144.990201         6543.0
std       0.971079  6.751564e+05  ...     0.099165            0.0
min       1.000000  1.310000e+05  ...   144.542370         6543.0
25%       2.000000  6.200000e+05  ...   144.926198         6543.0
50%       3.000000  8.800000e+05  ...   144.995800         6543.0
75%       4.000000  1.325000e+06  ...   145.052700         6543.0
max       8.000000  9.000000e+06  ...   145.526350         6543.0

[8 rows x 13 columns]

In [64]:
melb_df_copy.CouncilArea.ffill(inplace = True)

In [68]:
melb_df_copy.CouncilArea.isna().sum()

0

In [69]:
melb_df_copy.describe()

              Rooms         Price  ...    Longtitude  Propertycount
count  13580.000000  1.358000e+04  ...  13580.000000        13580.0
mean       2.937997  1.075684e+06  ...    144.995216         6543.0
std        0.955748  6.393107e+05  ...      0.103916            0.0
min        1.000000  8.500000e+04  ...    144.431810         6543.0
25%        2.000000  6.500000e+05  ...    144.929600         6543.0
50%        3.000000  9.030000e+05  ...    145.000100         6543.0
75%        3.000000  1.330000e+06  ...    145.058305         6543.0
max       10.000000  9.000000e+06  ...    145.526350         6543.0

[8 rows x 13 columns]

In [73]:
melb_df.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [76]:
melb_df.Car.value_counts()

2.0     5591
1.0     5509
0.0     1026
3.0      748
4.0      506
5.0       63
6.0       54
8.0        9
7.0        8
10.0       3
9.0        1
Name: Car, dtype: int64

Here, we can observe that there is a huge clash between number of cars as 1 or 2, but still as by median also we get 2, we will fill this with value as 2.

In [78]:
melb_df.Car.fillna(2, inplace = True)

In [84]:
area_mean = melb_df.BuildingArea.mean()
melb_df.BuildingArea.fillna(area_mean, inplace = True)

In [88]:
melb_df.CouncilArea.pad(inplace = True)

In [90]:
melb_df.YearBuilt.bfill(inplace = True)

In [91]:
melb_df.isna().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

This were the ways in which Data Cleaning is done. But a general and most important point is to understand your data and this will help you to do experiments with the data and will help you to understand the problem in hand better and will later help in miproving model's accuaracy